# ----------------------------
# ----------------------------
# Data Ingestion Configuration
# ----------------------------
# ----------------------------
# This file contains configurations for various data ingestion processes, 
# including scraping, loading, sorting, and pre-processing.

# ---------------------------
# Data Scraping Configuration
# ---------------------------
# Settings for scraping data from NOEMI reports and ATSPM event data from the Sunstore.

data_scraping:
  
  # General Settings
  # ----------------
  # Time (in seconds) to wait for pages to fully load before interacting with elements.
  wait_time: 5

  # List of supported web browsers for scraping data.
  # Currently configured to use Chrome only.
  browser_types:
    - "chrome"

  # NOEMI Report Scraping Configurations
  # ------------------------------------
  # Configuration settings for scraping reports from the NOEMI.
  
  noemi:
    # Base URL template for accessing individual reports. Replace "{}" with the SIIA ID to retrieve the report for a specific intersection.
    url: "https://noemi.cflsmartroads.com/ssv/report.html?id={}"
    
    # List of table IDs within the report to be extracted (identified by inspecting the HTML structure).
    table_ids:
      - "intersection"
      - "controller"
      - "approach"
      - "lanes"
    
    # Relative directory path for storing extracted tables from NOEMI reports.
    # Within this directory, each table will have its own sub-folder identified by table IDs.
    relative_report_export_parent_dir: "data/raw/atspm/fdot_d5/noemi_report"

  # Sunstore Event Data Scraping Configurations
  # -------------------------------------------
  # Configuration settings for scraping ATSPM event data from the Sunstore.
  
  sunstore:
    # Base URL for accessing the Sunstore portal.
    url: "https://sunstore.cflsmartroads.com"

    # Maximum number of login attempts allowed for accessing the Sunstore portal.
    max_attempts: 3

    # Column name in the Sunstore portal table representing the event date.
    date_column_name: "Date"

    # Column name in the Sunstore portal table containing the download link.
    link_column_name: "Download"

    # Relative directory path for storing ATSPM event data scraped from Sunstore.
    # Within this directory, sub-folders will be created by "year-month-day" for each date's event data in CSV format.
    relative_event_export_parent_dir: "data/raw/atspm/fdot_d5/event_data"

# --------------------------
# Data Sorting Configuration
# --------------------------
# Settings for sorting and organizing raw ATSPM event data from Sunstore.

data_sorting:

  # Sunstore Event Data Sorting Configuration
  # -----------------------------------------
  # Configuration settings for sorting ATSPM event data from Sunstore.

  sunstore:
    # Relative path to the directory containing sub-directories of raw ATSPM event data in CSV format.
    # Each sub-directory represents data from a specific date (formatted as "year-month-day").
    relative_event_import_parent_dir: "data/raw/atspm/fdot_d5/event_data"

    # Relative path the directory containing sub-directories for exporting the sorted and processed ATSPM data by signal ID and date.
    # Each signal's data is saved as a pickle file and csv files (for each date), organized in a structure that makes it easy to access and use.
    relative_event_export_parent_dir: "data/interim/atspm/fdot_d5/event_data"

# ---------------------------------
# Data Pre-processing Configuration
# ---------------------------------
# Settings for pre-processing raw NOEMI reports and ATSPM event data from sunstore.

data_preprocessing:

  # NOEMI Reports Pre-processing Configurations
  # -------------------------------------------
  # Settings for pre-processing NOEMI reports

  noemi:
    # Relative directory path to the directories containing tables from NOEMI reports
    relative_report_import_parent_dir: "data/raw/atspm/fdot_d5/noemi_report"

    # Name of the directory containing the "intersection" and "lane" report
    intersection_dir: "intersection"
    lane_dir: "lanes"

    # Mapping for renaming column names in the NOEMI "lane" report (by manual review)
    rename_map:
      Approach: approach
      Lane Type: laneType
      Width: width
      Length: length
      Lane No. from Left: laneNoFromLeft
      Type: type
      Channel: channelNo
      Phase: phaseNo
      Stopbar Distance: stopBarDistance
      Slot Number: slotNo

    # Relative directory path to export the pre-processed "intersection" and "lane" report (which represents the signal configuration)
    relative_report_export_dir: "data/interim/atspm/fdot_d5/signal_config"


# --------------------------------
# --------------------------------
# Feature Extraction Configuration
# --------------------------------
# --------------------------------
# This file contains configurations for various feature extraction processes, 
# including data quality check, and feature extraction.

# --------------------------------
# Data Quality Check Configuration
# --------------------------------
# This section contains settings for validating the quality of ATSPM event data
# from Sunstore and pre-processed NOEMI reports.

data_quality_check:

  # Sunstore Event Data Quality Check Configuration
  # -----------------------------------------------
  # Configuration for validating sequences and exporting data quality check results
  # for ATSPM event data scraped from the Sunstore portal.

  sunstore:
    # Define valid sequences for different types of event codes in ATSPM data.
    # These sequences help verify if event codes in the data match expected patterns.
    valid_event_sequence:
      
      # Expected event sequence for vehicle signal-related data checks
      vehicle_signal:
        - 1
        - 8
        - 10
        - 11

      # Expected event sequence for vehicle traffic-related data checks
      vehicle_traffic:
        - 82
        - 81

    # Relative directory path to sub-directories for importing ATSPM event data to be checked for quality.
    # Data within this sub-directories should be available by date and prepared for analysis.
    relative_event_import_parent_dir: "data/interim/atspm/fdot_d5/event_data"

    # Relative directory path to sub-directories where data quality check results will be exported.
    # The results will be stored per signal in subdirectories.
    relative_check_export_parent_dir: "data/proc/atspm/fdot_d5/data_quality_check"

  # NOEMI Reports Quality Check Configuration
  # ----------------------------------------
  # Configuration for importing NOEMI signal configuration data, which is required
  # to validate event sequences and ensure data consistency.

  noemi:
    # Relative directory path to import NOEMI signal configuration data.
    # This data is used to cross-reference ATSPM event data with known signal configurations.
    relative_config_import_dir: "data/interim/atspm/fdot_d5/signal_config"


# ---------------------------
# Feature Extraction Settings
# ---------------------------
# This section defines configurations for extracting specific features from ATSPM event data, 
# including expected event sequences and directory paths. The settings support validation, 
# sequence assignment, and feature profiling of vehicle, pedestrian, and traffic-related signals.

feature_extraction:

  # Sunstore Feature Extraction Configuration
  # ----------------------------------------
  # Configuration settings for extracting features and processing event sequences
  # from ATSPM event data retrieved from the Sunstore.

  sunstore:
    # Define valid sequences for various event types, which assist in validating
    # and extracting sequential events in the data for accurate feature profiling.
    valid_event_sequence:
      
      # Expected event sequence for vehicle signal-related feature extraction
      vehicle_signal:
        - 1
        - 8
        - 10
        - 11
    
      # Expected event sequence for pedestrian signal-related feature extraction
      pedestrian_signal:
        - 21
        - 22
        - 23

      # Expected event sequence for vehicle traffic-related feature extraction
      vehicle_traffic:
        - 82
        - 81

    # Relative path to the directory containing sub-directories with raw ATSPM event data.
    # Data should be organized by signal ID and date for processing and feature extraction.
    relative_event_import_parent_dir : "data/interim/atspm/fdot_d5/event_data"
            
    # Relative path to the directory where the extracted signal profiles (e.g., phase and cycle data)
    # will be saved, organized for easy access and further analysis.
    relative_signal_export_parent_dir : "data/proc/atspm/fdot_d5/feature_extraction/signal"
        

  # NOEMI Signal Configuration for Feature Extraction
  # ------------------------------------------------
  # Configuration settings for mapping signal phase numbers to barrier numbers 
  # based on signal configuration data, facilitating feature extraction.

  noemi:
    # Barrier map for assigning barrier numbers to phase numbers in configuration data.
    # This mapping aids in categorizing and profiling signal configurations during extraction.
    barrier_map:
      1: 2
      6: 2 
      2: 2
      5: 2
      3: 1
      8: 1
      4: 1
      7: 1

    # Relative path to the directory containing NOEMI configuration data,
    # which supports cross-referencing ATSPM event data with the associated signal configurations.
    relative_config_import_dir : "data/interim/atspm/fdot_d5/signal_config"

            














