# ----------------
# General Settings
# ----------------
# Relative base directory paths
relative_base_dir:
  raw: "data/raw"
  interim: "data/interim"
  production: "data/production"


# ----------------------------
# Data Ingestion Configuration
# ----------------------------
# Configurations for various data ingestion processes, 

data_scraping: # Settings for scraping data from NOEMI reports and ATSPM event data from Sunstore.
  
  # Time (in seconds) to wait for pages to fully load before interacting with elements.
  wait_time: 5

  # List of supported web browsers for scraping data.
  # Currently configured to use Chrome only.
  browser_types:
    - "chrome"
  

  # Configuration settings for scraping reports from the NOEMI.
  noemi: 

    # Base URL template for accessing individual reports. Replace "{}" with the SIIA ID to retrieve the report for a specific intersection.
    url: "https://noemi.cflsmartroads.com/ssv/report.html?id={}"
    
    # List of table IDs within the report to be extracted (identified by inspecting the HTML structure).
    table_ids:
      - "intersection"
      - "controller"
      - "approach"
      - "lanes"
    
    # Sequence of sub-directories (within base directory) for storing extracted tables from NOEMI reports.
    report_export_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "noemi_report"
    # - f"{table_id: 'intersection', 'controller', 'approach', 'lane'}" 


  # Configuration settings for scraping ATSPM event data from the Sunstore.
  sunstore:

    # Base URL for accessing the Sunstore portal.
    url: "https://sunstore.cflsmartroads.com"

    # Maximum number of login attempts allowed for accessing the Sunstore portal.
    max_attempts: 3

    # Column name in the Sunstore portal table representing the event date.
    date_column_name: "Date"

    # Column name in the Sunstore portal table containing the download link.
    link_column_name: "Download"

    # Sequence of sub-directories (within base directory) for storing ATSPM event data scraped from Sunstore.
    event_export_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "event_data"
    # - f"{year}-{month}-{day}"


data_sorting: # Settings for sorting and organizing raw ATSPM event data from Sunstore.

  # Configuration settings for sorting ATSPM event data from Sunstore.
  sunstore:

    # Sequence of sub-directories (within base directory) for importing ATSPM event data.
    event_import_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "event_data"
    # - f"{year}-{month}"

    # Sequence of sub-directories (within base directory) for exporting sorted ATSPM event data.
    event_export_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "event_data"
    # - f"{signal_id}"


data_preprocessing: # Settings for pre-processing raw NOEMI reports.

  # Settings for pre-processing NOEMI reports
  noemi:

    # Name of the directory containing the "intersection" and "lanes" tables
    intersection_dir: "intersection"
    lanes_dir: "lanes"

    # Mapping for renaming column names in the "lanes" table (by manual review)
    rename_map:
      Approach: approach
      Lane Type: laneType
      Width: width
      Length: length
      Lane No. from Left: laneNoFromLeft
      Type: type
      Channel: channelNo
      Phase: phaseNo
      Stopbar Distance: stopBarDistance
      Slot Number: slotNo

    # Sequence of sub-directories (within base directory) for importing "intersection" and "lanes" tables from NOEMI reports.
    report_import_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "noemi_report"
    # - f"{table_id: 'intersection', 'lanes'}"
    
    # Sequence of sub-directories (within base directory) for exporting signal configuration ("intersection" + "lanes" tables) data.
    config_export_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "signal_config"


# --------------------------------
# Feature Extraction Configuration
# --------------------------------
# Configurations for various feature extraction processes.

data_quality_check: # Settings for validating the quality of ATSPM event data

  # Configuration for validating sequences and exporting data quality check results
  sunstore:

    # Expected valid event sequences for different types of events.
    valid_event_sequence:
      
      # Expected event sequence for vehicle signal-related data checks
      vehicle_signal:
        - 1
        - 8
        - 10
        - 11

      # Expected event sequence for vehicle traffic-related data checks
      vehicle_traffic:
        - 82
        - 81

    # Sequence of sub-directories (within base directory) for importing sorted ATSPM event data.
    event_import_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "event_data"
    # - f"{signal_id}"

    # Sequence of sub-directories (within base directory) for exporting quality check results.
    check_export_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "data_quality_check"
    # - f"{event_type: vehicle_signal, vehicle_traffic}"


  # Configuration for importing NOEMI signal configuration data, which is required to validate event sequences.
  noemi:
   
    # Sequence of sub-directories (within base directory) for exporting signal configuration data.
    config_import_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "signal_config"


feature_extraction: # Configurations for extracting features from ATSPM event data

  # Settings for extracting features from ATSPM event data.
  sunstore:

    # Expected valid event sequences for various event types
    valid_event_sequence:
      
      # Expected event sequence for vehicle signal-related feature extraction
      vehicle_signal:
        - 1
        - 8
        - 10
        - 11
    
      # Expected event sequence for pedestrian signal-related feature extraction
      pedestrian_signal:
        - 21
        - 22
        - 23

      # Expected event sequence for vehicle traffic-related feature extraction
      vehicle_traffic:
        - 82
        - 81

    # Sequence of sub-directories (within base directory) for importing sorted ATSPM event data.
    event_import_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "event_data"
    # - f"{signal_id}"

    # Sequence of sub-directories (within base directory) for exporting vehicle and pedestrian signal profile.
    signal_export_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "feature_extraction"
      - "signal_profile"
    # - f"{resolution_level: phase, cycle}"
    # - f"{event_type: vehicle_signal, pedestrian_signal}"
    # - f"{signal_id}"
        

  # Settings for mapping signal phase numbers to barrier numbers based on signal configuration data to facilitate feature extraction.
  noemi:

    # Barrier map for assigning barrier numbers to phase numbers in configuration data.
    barrier_map:
      1: 2
      6: 2 
      2: 2
      5: 2
      3: 1
      8: 1
      4: 1
      7: 1

    # Sequence of sub-directories (within base directory) for exporting signal configuration data.
    config_import_sub_dirs: 
      - "atspm"
      - "fdot_d5"
      - "signal_config"




    